In [10]:
#cau 1
import numpy as np 
from math import acos, degrees
a = np.array([3,-2,1,4])
b = np.array([-1,5,0,2])
c = np.array([[2,-1,3],
             [1,4,-2],
             [0,2,-5]])
#a
Sum_ab= a + b
lin_comb = 2*a + 3*b
print("đáp án: ", Sum_ab)
print("đáp án: ", lin_comb)
#b
dot_product = np.dot(a, b)
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)
cos_theta = dot_product / (norm_a * norm_b)
angle_rad = acos(cos_theta)
angle_deg = round(degrees(angle_rad), 3)
print("đáp án: ", dot_product)
print("Góc giữa a và b:  ", angle_deg)
#c
CCT = np.dot(c, c.T)
print("C * C^T =")
print(CCT)

đáp án:  [2 3 1 6]
đáp án:  [ 3 11  2 14]
đáp án:  -5
Góc giữa a và b:   99.594
C * C^T =
[[ 14  -8 -17]
 [ -8  21  18]
 [-17  18  29]]


In [12]:
#cau 2
import numpy as np
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])
N = np.array([
    [1, 3, -2, 0],
    [-1, 5, 2, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])
#a
product = np.dot(M, N)
print("M * N =")
print(product)

#b
if M.shape[0] == M.shape[1]:
    det_M = round(np.linalg.det(M))
    print("Định thức của M =", det_M)
else:
    print("Không thể tính định thức vì M không phải ma trận vuông.")

#c 
rank_N = np.linalg.matrix_rank(N)
print("Hạng của ma trận N =", rank_N)


M * N =
[[  3   7   3  -5]
 [-18  24   0  30]
 [  7  19  22 -14]
 [-13   3   5  15]]
Định thức của M = 409
Hạng của ma trận N = 4


In [13]:
#cau 3 
import numpy as np
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])
b = np.array([6, 8, 3, 7])
#a
try:
    P_inv = np.linalg.inv(P)
    print("Ma trận nghịch đảo P^(-1):")
    print(np.round(P_inv, 3))
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch (det = 0)")
#b
x = np.dot(P_inv, b)
print("Nghiệm của hệ phương trình là:")
print(np.round(x, 3))
#c
b_check = np.dot(P, x)
print("Kiểm tra P * x:")
print("P * x =", np.round(b_check, 3))
print("So với b =", b)


Ma trận nghịch đảo P^(-1):
[[ 0.5    0.1    0.1   -0.3  ]
 [-0.143  0.2    0.057  0.114]
 [-0.036 -0.05   0.164  0.079]
 [-0.321 -0.05  -0.121  0.507]]
Nghiệm của hệ phương trình là:
[2.    1.714 0.429 0.857]
Kiểm tra P * x:
P * x = [6. 8. 3. 7.]
So với b = [6 8 3 7]


In [21]:
#cau 4
import numpy as np
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])
#a
#a
giatri_rieng, vector_rieng = np.linalg.eig(Q)
print("a) Các giá trị riêng của ma trận Q:")
for i in range(len(giatri_rieng)):
    val = giatri_rieng[i]
    print(f"  Giá trị riêng thứ {i+1} = {np.round(val, 4)}")
#b
print("\nb) Các vector riêng tương ứng với các giá trị riêng:")
for i in range(vector_rieng.shape[1]):
    vec = vector_rieng[:, i] 
    print(f"Vector riêng {i+1} = {np.round(vec, 4)}")
#c
print("\nc) Các vector riêng đã được chuẩn hóa (độ dài = 1):")
for i in range(vector_rieng.shape[1]):
    vec = vector_rieng[:, i]
    vec_chuanhoa = vec / np.linalg.norm(vec)
    print(f"Vector riêng {i+1} (chuẩn hóa) = {np.round(vec_chuanhoa, 4)}")



a) Các giá trị riêng của ma trận Q:
  Giá trị riêng thứ 1 = (6.3553+0j)
  Giá trị riêng thứ 2 = (2.8223+1.0773j)
  Giá trị riêng thứ 3 = (2.8223-1.0773j)

b) Các vector riêng tương ứng với các giá trị riêng:
Vector riêng 1 = [ 0.7485+0.j -0.1894+0.j  0.6356+0.j]
Vector riêng 2 = [-0.3742+0.3423j  0.0947+0.5743j  0.6356+0.j    ]
Vector riêng 3 = [-0.3742-0.3423j  0.0947-0.5743j  0.6356-0.j    ]

c) Các vector riêng đã được chuẩn hóa (độ dài = 1):
Vector riêng 1 (chuẩn hóa) = [ 0.7485+0.j -0.1894+0.j  0.6356+0.j]
Vector riêng 2 (chuẩn hóa) = [-0.3742+0.3423j  0.0947+0.5743j  0.6356+0.j    ]
Vector riêng 3 (chuẩn hóa) = [-0.3742-0.3423j  0.0947-0.5743j  0.6356-0.j    ]


In [26]:
#cau 5
import numpy as np
R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])
b = np.array([12, 5, 9])
#a
x = np.linalg.solve(R, b)
print("Nghiệm của hệ phương trình Rx = b là:")
print(np.round(x, 4))
#b
det_R = np.linalg.det(R)
print("Định thức của R =", round(det_R, 4))
if det_R != 0:
    print("=> R là ma trận khả nghịch.")
    R_inv = np.linalg.inv(R)
    print("Ma trận nghịch đảo của R:")
    print(np.round(R_inv, 4))
    x_inv = np.dot(R_inv, b)
    print("Nghiệm giải lại bằng ma trận nghịch đảo:")
    print(np.round(x_inv, 4))
    print("Hai nghiệm có giống nhau không", np.allclose(x, x_inv))
else:
    print("R không khả nghịch.")
#c
fro_norm = np.linalg.norm(R, 'fro')
print("Chuẩn Frobenius của ma trận R là:", round(fro_norm, 4))


Nghiệm của hệ phương trình Rx = b là:
[2.7882 1.5294 1.1882]
Định thức của R = 85.0
=> R là ma trận khả nghịch.
Ma trận nghịch đảo của R:
[[ 0.2235  0.1059 -0.0471]
 [-0.0588  0.2353  0.1176]
 [ 0.0235 -0.0941  0.1529]]
Nghiệm giải lại bằng ma trận nghịch đảo:
[2.7882 1.5294 1.1882]
Hai nghiệm có giống nhau không True
Chuẩn Frobenius của ma trận R là: 8.0
