In [ ]:

def scale(a, v): 
    return [a*vi for vi in v] 
v = [3,5,7]
scale(10, v)  
def sumvector(v, w): 
    return [vi+wi for (vi, wi) in zip(v, w)] 
v = [3,5,7] 
w = [2,4,6] 
sumvector(v, w) 
def dotvector(v, w):
    return sum([vi*wi for (vi, wi) in zip(v, w)]) 
dotvector(v, w)
def lenvector(v):  
    return dotvector(v,v) 
lenvector(w) 

56

In [ ]:
#Bài toán ứng dụng 1
#phân thành 2 loại 
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
scores >= 0
scores < 0 
np.select([scores >= 0, scores < 0], ['so duong', 'so am'], default='khong xac dinh')
#phân thành 3 loại 
import numpy as np
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
scores >=0
scores < 0
scores == 0
np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am'], default='khong xac dinh') 



array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U14')

In [77]:
#bài tập 3.1
import numpy as np 
from scipy import linalg, sparse
D = np.array([[3,4], [5,6]]) 
print (D)
C = np.array(np.random.random((5,7))) 
print(C)
A = np.array(np.random.random((2,2))) 
print (A)
b = np.array([(1+5j, 2j, 3j),(4, 5,6)]) 
B = np.asmatrix(b)
print (b) 
print (B)
print("Chuyển vị ma trận (đảo cột thành dòng và ngược lại): ")
print( A.T )
print("Ma trận nghịch đảo: ")
print(np.linalg.inv(A))
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]]) 
M_lower = np.tril(M)
print(M_lower) 
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M) 
print(M_upper)
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]]) 
v_diag = np.diag(M) 
print (v_diag) 
M_diag = np.diag(v_diag) 
print (M_diag) 



[[3 4]
 [5 6]]
[[0.44442178 0.89653259 0.58554303 0.3994168  0.33717532 0.44126736
  0.68355368]
 [0.02097653 0.78530505 0.6529929  0.68852936 0.28467072 0.00821425
  0.73920453]
 [0.0949381  0.79616731 0.87680912 0.43345378 0.26288137 0.66428115
  0.39251874]
 [0.9002569  0.55896606 0.78362143 0.47065564 0.36720292 0.31754043
  0.10192409]
 [0.6089438  0.73791858 0.53888302 0.24474677 0.51006837 0.45899625
  0.93951923]]
[[0.01663974 0.67072855]
 [0.68112531 0.25083307]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
Chuyển vị ma trận (đảo cột thành dòng và ngược lại): 
[[0.01663974 0.68112531]
 [0.67072855 0.25083307]]
Ma trận nghịch đảo: 
[[-0.55411122  1.48169544]
 [ 1.50466276 -0.03675858]]
[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]
[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]
[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [2]:
#bài tập dẫn nhập 
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
sp.solve([x*x+2-6, y-1-6, x+z-1, 2*x*x-8, z*z+4-5, y-z-8], [x,y,z])

x = [1, 2, 3]
y = [1, 2, 3]
print("So sánh x == y (1):", all([x[i] == y[i] for i in range(len(x))]))  # True

y = [1, 2, 4]
print("So sánh x == y (2):", all([x[i] == y[i] for i in range(len(x))]))  # False



import numpy as np

print("So sánh [1,2] và [1,2]:", np.array_equal([1, 2], [1, 2]))  # True
print("So sánh np.array([1,2]) và np.array([1,2]):", np.array_equal(np.array([1, 2]), np.array([1, 2])))  # True
print("So sánh np.array([1,2]) và np.array([1,2,3]):", np.array_equal(np.array([1, 2]), np.array([1, 2, 3])))  # False



So sánh x == y (1): True
So sánh x == y (2): False
So sánh [1,2] và [1,2]: True
So sánh np.array([1,2]) và np.array([1,2]): True
So sánh np.array([1,2]) và np.array([1,2,3]): False


In [3]:
#baitap3.2
import numpy as np
A = np.reshape(np.arange(36.0), (6, 6))
print("Ma trận A:")
print(A)
I6 = np.identity(6)
print("\nMa trận đơn vị I6:")
print(I6)
print("\nSố phần tử trong A:", A.size)
print("Đường chéo chính của A:", np.diagonal(A))
A = A + I6
print("\nMa trận A sau khi cộng với I6:")
print(A)
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print("\nTích A * vecB (C):")
print(C)
D = np.array([[1., 2., 3., 4., 5., 6.],
              [1., 0., 1., 0., 1., 0.]])
print("\nMa trận D (2x6):")
print(D)
E = A.dot(D.T)  
print("\nMa trận E = A * D.T:")
print(E)
F = np.array([
    [1., 1.],
    [2., 0.],
    [3., 1.],
    [4., 0.],
    [5., 1.],
    [6., 0.]
])
print("\nMa trận F (6x2):")
print(F)
G = A.dot(F)
print("\nMa trận G = A * F:")
print(G)
A_inv = np.linalg.inv(A)
print("\nMa trận nghịch đảo của A:")
print(A_inv)
print("\nnp.linalg.inv(np.linalg.inv(A)) có bằng A không?")
print(np.allclose(np.linalg.inv(np.linalg.inv(A)), A))

Ma trận A:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

Ma trận đơn vị I6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Số phần tử trong A: 36
Đường chéo chính của A: [ 0.  7. 14. 21. 28. 35.]

Ma trận A sau khi cộng với I6:
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]

Tích A * vecB (C):
[ 71. 198. 325. 452. 579. 706.]

Ma trận D (2x6):
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]

Ma trận E = A * D.T:
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]

Ma trận F (6x2):
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]

Ma trận G = A * F:
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]

Ma trận nghịch đảo của 

In [4]:
#bài toán ứng dụng 2
import numpy as np
A = np.array([[1, 1], [1, 0]])
b = np.array([1, 0])
n = 10
for i in range(n):
    b = A.dot(b)
    print(f"F({i+2}) = {b[0]}")

F(2) = 1
F(3) = 2
F(4) = 3
F(5) = 5
F(6) = 8
F(7) = 13
F(8) = 21
F(9) = 34
F(10) = 55
F(11) = 89


In [ ]:
#bài tập 5.2
import sympy as sp
from sympy import Symbol, solve
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
pt1 = x4 + 610 - 450 - x1      
pt2 = x1 + 400 - x2 - 640      
pt3 = x2 + 600 - x3          
pt4 = x3 - x4 - 520          
nghiem = solve((pt1, pt2, pt3, pt4))
print("Nghiệm của hệ phương trình là:")
print(nghiem)

In [11]:
#phương pháp ma trận
import numpy as np

# Ma trận hệ số A
A = np.array([
    [-1,  0,  0,  1],  
    [ 1, -1,  0,  0],  
    [ 0,  1, -1,  0],  
    [ 0,  0,  1, -1]  
])


b = np.array([160, 240, -600, 520]).reshape(4, 1)
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

print("Nghiệm gần đúng của hệ phương trình:")
print(x)

Nghiệm gần đúng của hệ phương trình:
[[-110.]
 [-270.]
 [ 410.]
 [ -30.]]


In [12]:
#bài tập 1
import numpy as np

A1 = np.array([[1, -1], [2, 3]])
b1 = np.array([2, 6])
x1 = np.linalg.solve(A1, b1)
print("Problem 1:", x1)

A2 = np.array([[1, -1, 0], [2, -1, -1], [1, 1, 1]])
b2 = np.array([2, 3, 6])
x2 = np.linalg.solve(A2, b2)
print("Problem 2:", x2)

A3 = np.array([
    [1, 1, 1],
    [4, 2, 1],
    [9, 3, 1]
])
b3 = np.array([4, 3, 4])
x3 = np.linalg.solve(A3, b3)
print("Problem 3 (a, b, c):", x3)

A4 = np.array([
    [1, 0, 1],
    [2, -2, -3],
    [-2, 2, 0]
])
b4 = np.array([1, -3, 0])
x4 = np.linalg.solve(A4, b4)
print("Problem 4 (a, b, c):", x4)

Problem 1: [2.4 0.4]
Problem 2: [3. 1. 2.]
Problem 3 (a, b, c): [ 1. -4.  7.]
Problem 4 (a, b, c): [0. 0. 1.]


In [ ]:
#bài tập 2
import sympy as sp

x, y, z, a, b, c = sp.symbols('x y z a b c')

sol1 = sp.solve([x - y - 2, 2*x + 3*y - 6], (x, y))
print("SymPy Problem 1:", sol1)

sol2 = sp.solve([x - y - 2, 2*x - y - z - 3, x + y + z - 6], (x, y, z))
print("SymPy Problem 2:", sol2)

sol3 = sp.solve([a + b + c - 4, 4*a + 2*b + c - 3, 9*a + 3*b + c - 4], (a, b, c))
print("SymPy Problem 3:", sol3)

sol4 = sp.solve([a + c - 1, a + b - 2*c + c + 3, -2*a + 2*b + c], (a, b, c))
print("SymPy Problem 4:", sol4)

In [ ]:
#bài tập 3
import numpy as np

def fib_matrix(k):
    F = np.array([[1, 1], [1, 0]], dtype=object)
    return np.linalg.matrix_power(F, k)

def fibonacci(n):
    fib = [0, 1]
    for i in range(2, n+1):
        fib.append(fib[-1] + fib[-2])
    return fib

# Ví dụ với k = 7
k = 7
Fk = fib_matrix(k)
fib_seq = fibonacci(k + 1)

print("F_k matrix:")
print(Fk)

print(f"Fibonacci sequence up to F_{k}:")
print(fib_seq)

print(f"Fk contains: Fib_{k+1}={fib_seq[k+1]}, Fib_{k}={fib_seq[k]}, Fib_{k-1}={fib_seq[k-1]}")
print("So Fk = [[Fib(k+1), Fib(k)], [Fib(k), Fib(k-1)]]:", Fk[0,0]==fib_seq[k+1], Fk[0,1]==fib_seq[k])