In [30]:
#bài tập 1.1
import numpy as np 
from scipy import linalg
a = np.array([1, 2, 3]) 
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]])
A = np.matrix(np.random.random( (2,2) ) ) 
B = np.asmatrix(b)
C = np.matrix(np.random.random((10,5)))
D = np.matrix([[4, 3], [2, 6]])
F = np.eye(3, k=1)
print("F = np.eye(3, k=1):\n", F)
F1 = np.eye(3, k=0)
print("F1 = np.eye(3, k=0):\n",F1) 
F3 = np.eye(3, k=-1) 
print("F3 = np.eye(3, k=-1) ", F3)
rank_C = np.linalg.matrix_rank(C)
print("\nHạng ma trận C:", rank_C)
try:
    inv_A = A.I
    print("\nMa trận nghịch đảo A.I:\n", inv_A)
except:
    print("\nMa trận A không khả nghịch (không thể tính A.I)")
try:
    inv_A_scipy = linalg.inv(A)
    print("\nMa trận nghịch đảo scipy.linalg.inv(A):\n", inv_A_scipy)
except:
    print("\nMa trận A không khả nghịch (không thể tính scipy.linalg.inv)")
det_A = linalg.det(A)
print("Định thức ma trận A:", det_A)
print("Chuyển vị A.T:", A.T)
print("Chuyển vị liên hợp A.H:", A.H)
b_vec = np.array([7, 5])
try:
    x = linalg.solve(A, b_vec)
    print("\nNghiệm hệ A x = b với b =", b_vec, ":\n", x)
except Exception as e:
    print("\nKhông giải được hệ phương trình:", e)
    E = np.mat(a).T
    print("\nMa trận cột E = np.mat(a).T:\n", E)
try:
    lstsq_res = linalg.lstsq(F0, E)
    print("\nGiải least squares linalg.lstsq(F, E):\n", lstsq_res)
except Exception as e:
    print("\nKhông giải được least squares:", e)
print("\nCộng ma trận np.add(A, D):\n", np.add(A, D))

print("\nTrừ ma trận np.subtract(A, D):\n", np.subtract(A, D))

print("\nChia ma trận np.divide(A, D):\n", np.divide(A, D))

print("\nNhân ma trận A @ D:\n", A @ D)

print("\nNhân từng phần tử np.multiply(D, A):\n", np.multiply(D, A))

print("\nTích np.dot(A, D):\n", np.dot(A, D))

print("\nTích vô hướng np.vdot(A, D):", np.vdot(A, D))
try:
    exp_A = linalg.expm(A)
    print("\nHàm mũ ma trận linalg.expm(A):\n", exp_A)
except Exception as e:
    print("\nKhông tính được expm(A):", e)
try:
    log_A = linalg.logm(A)
    print("\nHàm logarit ma trận linalg.logm(A):\n", log_A)
except Exception as e:
    print("\nKhông tính được logm(A):", e)


F = np.eye(3, k=1):
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
F1 = np.eye(3, k=0):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
F3 = np.eye(3, k=-1)  [[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]

Hạng ma trận C: 5

Ma trận nghịch đảo A.I:
 [[ 5.23215849 -7.81923219]
 [-3.90041559  7.43012645]]

Ma trận nghịch đảo scipy.linalg.inv(A):
 [[ 5.23215849 -7.81923219]
 [-3.90041559  7.43012645]]
Định thức ma trận A: 0.11936957524695573
Chuyển vị A.T: [[0.88693104 0.46559095]
 [0.93337843 0.62456054]]
Chuyển vị liên hợp A.H: [[0.88693104 0.46559095]
 [0.93337843 0.62456054]]

Nghiệm hệ A x = b với b = [7 5] :
 [-2.47105149  9.84772308]

Không giải được least squares: name 'F0' is not defined

Cộng ma trận np.add(A, D):
 [[4.88693104 3.93337843]
 [2.46559095 6.62456054]]

Trừ ma trận np.subtract(A, D):
 [[-3.11306896 -2.06662157]
 [-1.53440905 -5.37543946]]

Chia ma trận np.divide(A, D):
 [[0.22173276 0.31112614]
 [0.23279548 0.10409342]]

Nhân ma trận A @ D:
 [[5.414481   8.26106366]
 [3.11148488 5.14413608]]

N

In [ ]:
#baitap2.3
import numpy as np
A = np.array([ [0,1], [1,0]])
print(A)
temp = A.dot(A)
print(temp) 
k= 6
for i in range(k-1):
 temp = temp.dot(A)
 print (temp)
 print('---')
B = np.array([ [0,-1], [-1,0]])
print(B) 
temp = B.dot(B) 
print(temp) 
k= 5
for i in range(k-1):
 temp = temp.dot(B)
 print (temp)
 print('---')
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)
temp = C.dot(C)  
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print(temp) 
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print(temp) 


[[0 1]
 [1 0]]
[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[ 0 -1]
 [-1  0]]
[[1 0]
 [0 1]]
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
#baitap2.4
import numpy as np
M = np.array([ [0.8, 0.3], [0.2, 0.7]]) 
MM = M.dot(M)
print (MM) 
MM = M.dot(M) 
print (MM) 
for i in range(100):
 MM = MM.dot(M)
print (MM)

[[0.7  0.45]
 [0.3  0.55]]
[[0.7  0.45]
 [0.3  0.55]]
[[0.6 0.6]
 [0.4 0.4]]


In [24]:
#baitap3.2
import numpy as np
M = np.array([ [0.8, 0.3], [0.2, 0.7]]) 
P, L, U = linalg.lu(M) 
print (P) 
print (L)
print (U)  
L.dot(U)

[[1. 0.]
 [0. 1.]]
[[1.   0.  ]
 [0.25 1.  ]]
[[0.8   0.3  ]
 [0.    0.625]]


array([[0.8, 0.3],
       [0.2, 0.7]])

In [ ]:
#bài toán ứng dụng 2
import numpy as np
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]]) 
temp = A.dot(A) 
print(temp) 
temp = temp.dot(A) 
print(temp)

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [27]:
#tính tổng các ∑ A mũ i
import numpy as np
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]]) 
sumA = A
temp = A.dot(A)
k = 3 
sumA = sumA + temp
for i in range(1, k-1):
    temp = temp.dot(A)
    sumA = sumA + temp 
print(temp)
print(sumA)


[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


In [ ]:
# Câu 1
import numpy as np
A = np.array([[4, 2, 1],
              [3, 5, 2],
              [2, 1, 3]])

det_A = np.linalg.det(A)
print("Định thức của ma trận A =", det_A)

if det_A != 0:
    print("=> Ma trận A khả nghịch.")
    A_inv = np.linalg.inv(A)
    print("Ma trận nghịch đảo A⁻¹:\n", A_inv)
else:
    print("=> Ma trận A không khả nghịch.")
input_text = "Nguyen Van A" 
def text_to_vectors(text):
    ascii_codes = [ord(ch) for ch in text]
    while len(ascii_codes) % 3 != 0:
        ascii_codes.append(0)  
    matrix = np.array(ascii_codes).reshape(-1, 3).T
    return matrix
vecs = text_to_vectors(input_text)
print("Vector mã ASCII:\n", vecs)
encoded = A @ vecs
print("Kết quả mã hóa:\n", encoded)
decoded = A_inv @ encoded
decoded = np.round(decoded).astype(int)

decoded_text = ''.join([chr(val) for val in decoded.T.flatten() if val != 0])
print("Giải mã:\n", decoded_text)


Định thức của ma trận A = 35.00000000000001
=> Ma trận A khả nghịch.
Ma trận nghịch đảo A⁻¹:
 [[ 0.37142857 -0.14285714 -0.02857143]
 [-0.14285714  0.28571429 -0.14285714]
 [-0.2         0.          0.4       ]]
Vector mã ASCII:
 [[ 78 121  32 110]
 [103 101  86  32]
 [117 110  97  65]]
Kết quả mã hóa:
 [[ 635  796  397  569]
 [ 983 1088  720  620]
 [ 610  673  441  447]]
Giải mã:
 Nguyen Van A


In [ ]:
#câu 2
import numpy as np
def continued_fraction(coeffs):
    M = np.array([[1, 0], [0, 1]])
    for c in coeffs:
        M_c = np.array([[c, 1], [1, 0]])
        M = M @ M_c
    pn, pn_1 = M[0, 0], M[0, 1]
    qn, qn_1 = M[1, 0], M[1, 1]
    return pn, qn
coeffs = [2, 1, 2]
pn, qn = continued_fraction(coeffs)
print(f"Kết quả: {pn}/{qn}")

Kết quả: 8/3
