In [5]:
#baitap1.1
import numpy as np
D = np.array([[1,2],[3,4]])
E= np.array([[1,2],[3,5]])
np.copyto(E,D)
np.copyto(E,D)
print(E)

[[1 2]
 [3 4]]


In [15]:
#baitap1.3
from numpy import matlib
G = matlib.identity(5)
print(G)
H = matlib.randn(3, 2)
print(H)
K = matlib.zeros([4,4])
print(K) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[-0.65551616 -0.73094366]
 [ 1.09143009 -0.27741626]
 [-0.33053377 -0.58416613]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
#baitap2.2
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2] 
M = np.matrix([[1,2],[3,4]]) 
for i in range(len(c)):
    ci = np.matrix([[1,1],[1,0]])
    ci[0, 0] = c[i]
    if (i==0):
        M = ci
    else:
        M = M.dot(ci) 
print(M)
print (M[0,0]/M[1,0]) 


[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


In [19]:
import numpy as np

X = np.array([[1, 2], [3, 4]])
Y = np.array([[5], [6]])
XT = X.T
A1 = np.linalg.inv(X).dot(X)
A2 = np.linalg.inv(X).dot(Y)
A = A1.dot(A2)
print("A1 =\n", A1)
print("A2 =\n", A2)
print("A =\n", A)

A1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
A2 =
 [[-4. ]
 [ 4.5]]
A =
 [[-4. ]
 [ 4.5]]


In [24]:
import numpy as np
def bpcuctieu(a): 
    b = []
    o1 = []
    for i in range(len(a)): 
        o1.append(1.0)
        b.append((i+1)*1.0) 
    x = np.array([o1, b])
    u = np.dot(x, x.T)
    y = np.array(a)
    from numpy import linalg 
    u_1 =np.linalg.inv(u)
    v = np.dot(u_1, x) 
    A = np.dot(v, y)
    return A 
dulieu = [10.0, 8, 7, 5, 2]
A = bpcuctieu(dulieu)
print(f"Phương trình tuyến tính: y = {A[0]:.1f} + ({A[1]:.1f})·x")

Phương trình tuyến tính: y = 12.1 + (-1.9)·x
