In [6]:
#cau 1
import numpy as np
from numpy.linalg import norm
from numpy import dot, arccos, degrees
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([
    [1, 2, -1],
    [0, 3, 4],
    [2, -1, 0]
])
tong = A + B
bieuthuc = 3 * A - 2 * B
print("a) A + B =", tong)
print("a) 3A - 2B =", bieuthuc)
tich_vo_huong = dot(A, B)
goc = degrees(arccos(tich_vo_huong / (norm(A) * norm(B))))
print("b) A · B =", tich_vo_huong)
print("b) Góc giữa A và B =", round(goc, 3), "độ")
Ct = C.T
CtC = np.dot(Ct, C)
print("c) C^T · C =\n", CtC)

a) A + B = [3 3 1 5]
a) 3A - 2B = [  4 -11  13 -10]
b) A · B = -8
b) Góc giữa A và B = 108.376 độ
c) C^T · C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [7]:
#cau 2
import numpy as np
from numpy.linalg import det
from numpy.linalg import matrix_rank
M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])

N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

tich_MN = np.dot(M, N)
print("a) M x N =", tich_MN)
dinh_thuc_M = det(M)
print("b) Định thức của M =", round(dinh_thuc_M, 3))
hang_N = matrix_rank(N)
print("c) Hạng của N =", hang_N)

a) M x N = [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]
b) Định thức của M = 0.0
c) Hạng của N = 2


In [8]:
#cau 3
import numpy as np
from numpy.linalg import inv, LinAlgError
P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])

b = np.array([4, 7, 9, 5])
print("a) Ma trận nghịch đảo của P:")
try:
    P_inv = inv(P)
    print(np.round(P_inv, 3))  
except LinAlgError:
    print("Ma trận P không khả nghịch (det(P) = 0).")
print("\nb) Giải hệ phương trình:")
x = np.dot(P_inv, b)
print("Nghiệm x =", np.round(x, 3))
print("\nc) Kiểm tra nghiệm (P · x = b):")
b_kiemtra = np.dot(P, x)
print("P · x =", b_kiemtra)
print("b =", b)
print("Sai số tuyệt đối =", np.abs(b_kiemtra - b))

a) Ma trận nghịch đảo của P:
[[ 0.488 -0.093  0.023 -0.209]
 [ 0.035  0.279 -0.07   0.128]
 [-0.116  0.07   0.233 -0.093]
 [-0.012 -0.093  0.023  0.291]]

b) Giải hệ phương trình:
Nghiệm x = [0.465 2.105 1.651 0.965]

c) Kiểm tra nghiệm (P · x = b):
P · x = [4. 7. 9. 5.]
b = [4 7 9 5]
Sai số tuyệt đối = [0.00000000e+00 1.77635684e-15 0.00000000e+00 0.00000000e+00]


In [ ]:
#cau 4
import numpy as np
from numpy.linalg import eig, norm
Q = np.array([
    [4, -1, 0],
    [1, 3, -2],
    [0, 1, 2]
])
eigenvalues, eigenvectors = eig(Q)
print("a) Các giá trị riêng (eigenvalues) của Q:")
for i, val in enumerate(eigenvalues, 1):
    print(f"  λ{i} = {np.round(val, 4)}")
print("b) Các vector riêng tương ứng (chưa chuẩn hóa):")
for i, vec in enumerate(eigenvectors.T, 1):
    print(f"  v{i} = {np.round(vec, 4)}")
print("c) Vector riêng đã chuẩn hóa (độ dài = 1):")
for i, vec in enumerate(eigenvectors.T, 1):
    normed = vec / norm(vec)
    print(f"  v{i}_normalized = {np.round(normed, 4)}")


a) Các giá trị riêng (eigenvalues) của Q:
  λ1 = (3.4534+0j)
  λ2 = (2.7733+1.4677j)
  λ3 = (2.7733-1.4677j)
b) Các vector riêng tương ứng (chưa chuẩn hóa):
  v1 = [0.8333+0.j 0.4555+0.j 0.3134+0.j]
  v2 = [-0.2621-0.3135j -0.7817+0.j     -0.2196+0.4169j]
  v3 = [-0.2621+0.3135j -0.7817-0.j     -0.2196-0.4169j]
c) Vector riêng đã chuẩn hóa (độ dài = 1):
  v1_normalized = [0.8333+0.j 0.4555+0.j 0.3134+0.j]
  v2_normalized = [-0.2621-0.3135j -0.7817+0.j     -0.2196+0.4169j]
  v3_normalized = [-0.2621+0.3135j -0.7817+0.j     -0.2196-0.4169j]


In [11]:
#cau 5
import numpy as np
from numpy.linalg import solve, inv, det, norm
R = np.array([
    [1, -2, 3],
    [2, 0, 1],
    [-1, 1, 4]
])
b = np.array([10, 8, 7])
x1 = solve(R, b)
print("a) Nghiệm hệ phương trình Rx = b bằng np.linalg.solve():")
print("   x =", np.round(x1, 4))
print("\nb) Kiểm tra khả nghịch và giải bằng ma trận nghịch đảo:")
if det(R) != 0:
    R_inv = inv(R)
    x2 = R_inv @ b
    print("   Ma trận R khả nghịch.")
    print("   Ma trận nghịch đảo R^(-1):\n", np.round(R_inv, 4))
    print("   Nghiệm hệ bằng nghịch đảo: x =", np.round(x2, 4))
    print("   So sánh hai nghiệm (x1 == x2?):", np.allclose(x1, x2))
else:
    print("   Ma trận R không khả nghịch (det(R) = 0)")
fro_norm = norm(R, 'fro')
print("\nc) Chuẩn Frobenius của ma trận R:", np.round(fro_norm, 4))


a) Nghiệm hệ phương trình Rx = b bằng np.linalg.solve():
   x = [2.7826 0.0435 2.4348]

b) Kiểm tra khả nghịch và giải bằng ma trận nghịch đảo:
   Ma trận R khả nghịch.
   Ma trận nghịch đảo R^(-1):
 [[-0.0435  0.4783 -0.087 ]
 [-0.3913  0.3043  0.2174]
 [ 0.087   0.0435  0.1739]]
   Nghiệm hệ bằng nghịch đảo: x = [2.7826 0.0435 2.4348]
   So sánh hai nghiệm (x1 == x2?): True

c) Chuẩn Frobenius của ma trận R: 6.0828
